Features/entities/GiveTutorial
CSC207-2022F-UofT/course-project-group-105 pull request #23
Opened 2022-10-28 01:50 UTC by zhaoan12

Testing the push and pull request functions in git by adding a partially complete GiveTutorial entity which stores data for keeping track of the player's actions in the tutorial.

2022-10-30 20:28 UTC, sbrad044 approved these changes

2022-10-30 22:01 UTC, siddharthgowda submitted a review, later dismissed

2022-11-01 02:09 UTC, 6167656e74323431 requested changes
Also missing javadoc.

2022-11-01 02:09 UTC, 6167656e74323431 commented on src/main/java/com/mg105/entities/GiveTutorial.java
> +    private boolean UsedItem = false;
Sytle: Usually we use `camelCase` not `PascalCase` in java for class fields.

2022-11-02 17:17 UTC, siddharthgowda approved these changes

2022-11-04 00:49 UTC, 6167656e74323431 approved these changes
LGTM

2022-11-04 00:51 UTC, sbrad044 approved these changes

2022-11-04 00:52 UTC, merged

2022-11-04 00:52 UTC, 6167656e74323431 commented
Merged during weekly meeting.