Implementation of Battle, BattleCharacter, and Move classes.
CSC207-2022F-UofT/course-project-group-105 pull request #25
Opened 2022-10-30 01:42 UTC by m-grigoriu

This pull request is for the implementation of three Battle related entities.

Move has health damage, strength damage, caster and target attributes, each with a getter function, and one setter function for target. The caster and target instances might be unnecessary depending on how the rest of the program is implemented, but they could be useful for keeping track of character animations.

BattleCharacter has health, damage, and speed attributes, along with a list of two moves. There are getter functions for each of the three stats, and one for each of the two moves in the list. There is no implementation for the discussed 'sprite' instance yet. There are also methods to modify the health and attack stats of the entity, and the class implements Comparable for use in the Battle class.

Battle a battleStatus attribute, along with a getter function (there is no setter function, but one could be added if the option to forfeit a combat encounter is discussed). There is also a numTokens attribute, with a getter and setter function. There are ArrayList attributes for the player characters and the opponents, each with their own getter function, and a moveQueue instance which contains every character in the previous two lists sorted by their speed. There is a method to get the next character to move from the queue, which dequeues them from the list and enqueues them again. Finally, there is a method to remove a BattleCharacter from either of the two character lists and from the moveQueue. This method will update the  battleStatus if one of the two parties becomes empty.

2022-10-30 20:26 UTC, sbrad044 approved these changes

2022-10-30 22:01 UTC, siddharthgowda approved these changes
Looks good (only thing is that BattleCharacter needs name attribute and stat increasing functions)

2022-10-31 14:32 UTC, siddharthgowda requested changes
So for battleCharacter there should be a name for each character and there should be a maxHealth attribute (so upgrade tokens can increase maxHealth). Also there should be functions that can increase maxHealth, dmg, speed (so the user can increase them via upgrade tokens)

2022-10-31 19:22 UTC, hoodiexxx commented
look pretty wholesome and functional. For getBattleStatus() method in Battle.java it might could add an if else statement and return win lose in string form.

2022-10-31 21:38 UTC, hoodiexxx approved these changes
wholesome coding and looks functional

2022-10-31 21:38 UTC, hoodiexxx commented on src/main/java/com/mg105/entities/Battle.java
> +    }
Personally, I prefer writing an if else statement and return "win", "lose" or "in progress" in string form but it is fine for returning -1,0,1 coercion.

2022-11-01 00:57 UTC, siddharthgowda approved these changes

2022-11-04 00:54 UTC, 6167656e74323431 approved these changes
LGTM

2022-11-04 01:03 UTC, siddharthgowda approved these changes
This mostly looks very good! The only issues I have is that there might be some open closed principle violations in your battleCharacter moves attributes (since you have hard coded that their is only two moves)

2022-11-04 01:06 UTC, zhaoan12 approved these changes
Looks good. You have many variables so I would suggest having a way to track all of them outside the program.

2022-11-04 01:09 UTC, merged

2022-11-04 01:09 UTC, 6167656e74323431 commented
Merged during weekly meeting.