Inventory and Item
CSC207-2022F-UofT/course-project-group-105 pull request #27
Opened 2022-10-31 19:28 UTC by siddharthgowda

I accidentally created a new branch of Inventory and Item (so I deleted the old branch and its pull request)

Essentially here I am just making the entities for items (and its subclasses) and inventory. I also made a class that contains the name and description of item subclasses because those names will be needed in multiple classes (specifically the InventoryInteractor). I also made some minor refactoring changes (made a subfolder called items).

2022-10-31 20:29 UTC, sbrad044 submitted a review, later dismissed

2022-10-31 21:13 UTC, 6167656e74323431 requested changes

2022-10-31 21:13 UTC, 6167656e74323431 commented on src/main/java/com/mg105/entities/Item.java
> +    final public String DESCRIPTION;
`ALL_CAPS` is for public final static things (true constants).

2022-10-31 21:35 UTC, hoodiexxx submitted a review, later dismissed
good coding

2022-10-31 21:35 UTC, hoodiexxx commented on src/main/java/com/mg105/entities/Inventory.java
> +            }
smart implementation

2022-10-31 21:44 UTC, 6167656e74323431 approved these changes
YES!

2022-10-31 21:47 UTC, 6167656e74323431 approved these changes

2022-10-31 21:54 UTC, hoodiexxx submitted a review, later dismissed
The code looks well made and it seems cover all the corner cases in the InventoryTest.java.

2022-10-31 23:23 UTC, zhaoan12 commented on src/main/java/com/mg105/entities/items/HealthPotion.java
> +    public final static int HEALING_POINTS = 25;
Nice class! After playtesting our game we can always change the value of healing points to provide a balanced game for the player.

2022-10-31 23:24 UTC, zhaoan12 submitted a review, later dismissed
Well made classes.

2022-11-01 04:34 UTC, m-grigoriu submitted a review, later dismissed
Everything looks good. There should eventually be a useItem() method, either in the Item class or the Inventory class (depending on which implementation is preferable). I am also not sure how useful a separate file for item constants is, unless we plan on having a large number of items and want one file where we can see every detail at once.

2022-11-01 19:35 UTC, 6167656e74323431 approved these changes
Fine.

Although please create Github issues for missing documentation/tests.

2022-11-04 00:37 UTC, 6167656e74323431 approved these changes

2022-11-04 00:40 UTC, zhaoan12 approved these changes

2022-11-04 00:45 UTC, sbrad044 approved these changes

2022-11-04 00:46 UTC, merged

2022-11-04 00:48 UTC, 6167656e74323431 commented
Merged during weekly meeting.