features/UI/GameWindow
CSC207-2022F-UofT/course-project-group-105 pull request #32
Opened 2022-11-03 00:44 UTC by zhaoan12

Added javafx stuff to build.gradle and created a test game window with test text.  You might need to go on Run -> Edit Configurations, and add these VM options for it to work:   --module-path "\path\to\javafx-sdk-19\lib" --add-modules javafx.controls,javafx.fxml

2022-11-03 01:07 UTC, 6167656e74323431 requested changes

2022-11-03 01:07 UTC, 6167656e74323431 commented on build.gradle
> +}
You have not completely configured gradle properly... it should get to the point where you only have to run `./gradlew run`, and that will download all the dependencies automatically.

2022-11-04 01:17 UTC, sbrad044 approved these changes

2022-11-04 01:28 UTC, 6167656e74323431 approved these changes
LGTM

2022-11-04 01:31 UTC, siddharthgowda approved these changes

2022-11-04 01:32 UTC, merged

2022-11-04 01:32 UTC, 6167656e74323431 commented
Merged during weekly meeting.