Replay implementation
CSC207-2022F-UofT/course-project-group-105 pull request #44
Opened 2022-11-12 23:31 UTC by hoodiexxx

incomplete implementation, need to amend later. exactly implementation should depend on other use cases' implementation.

2022-11-13 07:51 UTC, sbrad044 reviewed
Good start. If this is duplicating the changes in Theo's pull request, are we allowed to approve both or do we have to change one of them?

2022-11-13 23:02 UTC, 6167656e74323431 commented
> If this is duplicating the changes in Theo's pull request, are we allowed to approve both or do we have to change one of them?

Under the hood, as it would turn out, the duplicated changes are the **same** changes, so as it turns out merging this is equivalent* to merging #42 and then this (but this is not true if we merge this and then #42).

*almost... you can look into git internals yourself, *if you dare*.

2022-11-13 23:34 UTC, siddharthgowda submitted a review, later dismissed
This looks good only thing is that some methods will change based on the implementation of the other features. I know this was already mentioned for some of the methods but there are other methods where this also applies.

2022-11-13 23:40 UTC, 6167656e74323431 requested changes
Correct me if I'm wrong, but it does not look like IDEA-formatted code.

See [this](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat_module_directory).

2022-11-13 23:40 UTC, 6167656e74323431 commented on src/main/java/com/mg105/entities/Inventory.java
> +    }
Style: this does not look like the automatic formatter was run.

2022-11-13 23:40 UTC, 6167656e74323431 commented on src/main/java/com/mg105/use_cases/ReplayGenerator.java
> +    }
Style: this does not look like the automatic formatter was run.

2022-11-14 21:17 UTC, zhaoan12 approved these changes
Nice classes and methods. Since you did not give any test cases, maybe some ideas for the test case are to give the player extra stats in addition to their base stats. Then, use the replay generator to make a new game and see if the stats are retained.

2022-11-14 21:17 UTC, zhaoan12 commented on src/main/java/com/mg105/entities/GameState.java
> +     * Get the room the player happes to currently be in.
spelling error: change happes to happens

2022-11-14 21:17 UTC, zhaoan12 commented on src/main/java/com/mg105/entities/Doorway.java
> +    private final Point position;
I like how you gave a better name for the variable.

2022-11-14 21:17 UTC, zhaoan12 commented on src/main/java/com/mg105/entities/GameState.java
> +        return currentRoom == firstRoom;
Nice method, I will use it when implementing the tutorial.

2022-11-15 04:18 UTC, 6167656e74323431 requested changes

2022-11-15 04:18 UTC, 6167656e74323431 commented on src/main/java/com/mg105/use_cases/ReplayGenerator.java
> +    public BattleCharacter AttributeInheritance(BattleCharacter battleCharacter) {
Style: we use `camelCase` for functions in Java... not `PascalCase`. Note: you do this in muptiple places but I will only highlight the first one I see.

2022-11-16 00:28 UTC, siddharthgowda requested changes
Overall, it looks pretty good. The only thing is that there is no javadoc for the classes. Also make sure when you write the java doc that it is above the class.

2022-11-28 18:30 UTC, 6167656e74323431 commented
Question, what are the licensing terms of `imgs/gamelose.jpg`? Are we allowed to use it copyright-wise?

2022-12-02 03:23 UTC, 6167656e74323431 commented
Note: background2 i licensed under CC Attribution-NonCommercial-NoDerivs 2.0 Generic (CC BY-NC-ND 2.0)
Fred Seibert

2022-12-04 03:10 UTC, m-grigoriu submitted a review, later dismissed
Everything looks good.

2022-12-04 03:12 UTC, 6167656e74323431 requested changes

2022-12-04 03:12 UTC, 6167656e74323431 commented on src/main/java/com/mg105/interface_adapters/Toggler.java
> +
Docstrings removed? Ad them back pls.

2022-12-04 03:12 UTC, 6167656e74323431 commented on src/main/java/com/mg105/user_interface/ReplayGeneratorButton.java
> +import javax.swing.*;
This import should be removed (we don't use swing afaik)

2022-12-04 03:15 UTC, zhaoan12 approved these changes
Nice class

2022-12-04 03:15 UTC, zhaoan12 commented on src/main/java/com/mg105/use_cases/ReplayGenerator.java
> +    public ArrayList<BattleCharacter> attributeInheritance() {
need doctring i think

2022-12-04 03:16 UTC, 6167656e74323431 requested changes
See my earlier comments

2022-12-04 03:24 UTC, 6167656e74323431 approved these changes

2022-12-04 03:27 UTC, zhaoan12 approved these changes
Nice changes

2022-12-04 03:28 UTC, m-grigoriu approved these changes

2022-12-04 03:28 UTC, merged