features/Tutorial
CSC207-2022F-UofT/course-project-group-105 pull request #46
Opened 2022-11-14 21:35 UTC by zhaoan12

Updated javadoc on GiveTutorial entity. Create a new use cases class that tracks the current "phase" of the tutorial, whether the tutorial is completed, and is able to change the status of different tutorial actions. Created test cases for multiple methods in the class. Added a Utils class that contains Strings for the tutorial.

2022-11-14 22:50 UTC, sbrad044 approved these changes

2022-11-14 22:50 UTC, sbrad044 commented on src/main/java/com/mg105/use_cases/PlayerGetsTutorial.java
> +     * Get current phase of tutorial, which is first index of phase list
why/how is the current phase always the first index?

2022-11-14 22:50 UTC, sbrad044 commented on src/main/java/com/mg105/entities/GiveTutorial.java
> +    public GiveTutorial(boolean moved, boolean attacked, boolean usedItem){
why not just have these variables set to false by default? unless there's a scenario in which the user can redo certain parts of the tutorial I guess. I assumed the tutorial would be a one time thing

2022-11-15 04:23 UTC, 6167656e74323431 requested changes
In addition to the comments the autoformatter clearly hasn't been run. Use it please.

Content-wise it seems fine.

2022-11-15 04:23 UTC, 6167656e74323431 commented on src/main/java/com/mg105/use_cases/PlayerGetsTutorial.java
> +     */
Javadoc is incorrect. There should be at least one `@param` for the missing argument.

2022-11-16 00:55 UTC, siddharthgowda commented on src/main/java/com/mg105/use_cases/PlayerGetsTutorial.java
> +    }
It seems redundant to have the completed attribute and having this method as well. Also these values are probably better off put as constants although that really isn't a big deal.

2022-11-16 01:01 UTC, siddharthgowda requested changes
Overall things seem pretty good. Some of the things in the usecase could also have been placed in the entity layer (not saying that putting it in the usecase layer was wrong, it's just another option). Also look at my comment.

2022-11-18 15:46 UTC, closed without merging