Added non-UI battle classes, changed existing battle related entities.
CSC207-2022F-UofT/course-project-group-105 pull request #54
Opened 2022-11-20 00:43 UTC by m-grigoriu

Added new attributes to BattleCharacter and Move classes for better identification (such as name). Added method to Battle to translate from name string to BattleCharacter object for communication between the View, Presenter, and Model. Modified removeChar method in Battle to return void since the battleStatus will get verified regardless of if it gets changed here or not. Added currEncounter, party, and fainted attributes to GameState with getter and setter (only for currEncounter) functions. Added Party creation code to GameState constructor.

Created "BattlePresenter" class following MVP pattern.
- Contains reference to GameState, a specific Battle instance, and the view.
- createEncounter() creates a new Battle instance with random opponent BattleCharacters, sets it as currEncounter in GameState.
- contains methods to give BattleCharacter data to View using a character name string as a parameter
- roundStart() executes a round of the encounter. If encounter has been won/lost, call endBattle() or a method in ReplayGenerator, respectively. If in progress, dequeue the next moving character, make a move if they are an opponent, return the moving character name no matter what side is moving.
- If a player character is moving, call retrieveTargets() with the chosen move number and moving character name to retrieve a list of the characters who can be targeted.
- _useMove() applies a move used by a caster character onto a target character. It also removes a character from the game if it faints and updates the party in GameState if a player character faints. Moves that are meant to deal damage are amplified (or nullified if damage stat is negative) based on the moving character's damage stat (can be discussed).
- executeTurn() is called from View and is used to execute a move when the moving character is a player character
- endBattle(), _removeActiveBattle, _addReward() {all unimplemented} deal with what happens when combat ends.

Created unimplemented view class "BattleMenu"

2022-11-20 03:21 UTC, 6167656e74323431 commented
I assume this fixes #34 ?

2022-11-20 21:07 UTC, sbrad044 submitted a review, later dismissed

2022-11-21 00:16 UTC, 6167656e74323431 requested changes
Check your package names, eg. I'm pretty sure we use `[nterface_adapters` not `interfaceadapter`, etc.

2022-11-21 19:21 UTC, siddharthgowda requested changes
Overall this looks very good. The only thing is that there were many places (specifically in the presenter) where you should constants instead of hard coding strings. Besides that and some things with battle status (looks at my comments) everything else looks good.

2022-11-21 19:21 UTC, siddharthgowda commented on src/main/java/com/mg105/user_interface/BattleMenu.java
> +            Integer.toString(opponentDmg[3]));
Since you use these string multiple times you might want to use constants here

2022-11-21 19:21 UTC, siddharthgowda commented on src/main/java/com/mg105/entities/Battle.java
> +    }
You never set battle status 1 is the user has won the battle. I'm not sure if needs to be here or somewhere else but it should be implemented somewhere

2022-11-21 21:23 UTC, siddharthgowda approved these changes
Still need to make some constants instead of hardcdoing strings. But everything else is good (approved).

2022-11-21 21:25 UTC, 6167656e74323431 approved these changes

2022-11-21 21:28 UTC, zhaoan12 approved these changes
Nice classes and methods.

2022-11-21 21:28 UTC, zhaoan12 commented on src/main/java/com/mg105/user_interface/BattleMenu.java
> +    public void setNames(String[] playerNames, String[] opponentNames) {
you need docstring for this function

2022-11-21 21:30 UTC, merged