Inventory Presenter, Controller, UI
CSC207-2022F-UofT/course-project-group-105 pull request #62
Opened 2022-11-24 21:28 UTC by siddharthgowda

This pull request includes the classes for the presenter, controller and ui, and their respective interfaces. The control of flow  goes from a call to the controller and a response that is send to the presenter which updates the UI. Not all of the type annotations are done (like not null) and the ui is not implemented with the scene controller yet but I will do that in a separate branch after the pull request.

2022-11-25 01:40 UTC, 6167656e74323431 requested changes
Mostly good, although the package names seem very out of line compared to the rest of the codebase.

2022-11-25 01:40 UTC, 6167656e74323431 commented on src/main/java/com/mg105/entities/Item.java
>       */
Deleted method, forgot to delete javadoc

2022-11-25 01:40 UTC, 6167656e74323431 commented on src/main/java/com/mg105/view_interfaces/Alert.java
> +package com.mg105.view_interfaces;
We are organizing our code by layer, `view_interfaces` is not one of the clean architecture layers. If this is only needed in the user interface (which as far as I can tell is true), it should just be in the `user_interface` package...?

2022-11-25 04:11 UTC, 6167656e74323431 submitted a review, later dismissed
LGTM

2022-11-28 01:58 UTC, m-grigoriu commented on src/main/java/com/mg105/user_interface/inventory/InventoryDisplay.java
> +    private String getCharacterSelected() {
Since this is a private method, why not just write this.characterSelected wherever you call it instead?

2022-11-28 02:02 UTC, m-grigoriu submitted a review, later dismissed
Everything looks good.

2022-11-28 17:59 UTC, sbrad044 approved these changes

2022-11-28 22:09 UTC, hoodiexxx approved these changes
Good Implementation

2022-11-28 22:10 UTC, hoodiexxx approved these changes

2022-11-28 22:10 UTC, hoodiexxx commented on src/main/java/com/mg105/Application.java
> +            new InventoryInteractor(state, inventoryPresenter)));
nice coding

2022-11-28 22:11 UTC, 6167656e74323431 approved these changes

2022-11-28 22:17 UTC, zhaoan12 approved these changes
Nice changes

2022-11-28 22:20 UTC, merged