Data Access
CSC207-2022F-UofT/course-project-group-105 pull request #69
Opened 2022-11-29 23:57 UTC by siddharthgowda

This branch has classes are that interactor with a "database" (just two csvs). I used an external openCSV package and updated the build.gradle with this (please make sure this works on your machine). I also made classes updates the database. Also, I made a class that should be called in main and constructors the party and sets it in game state (I did not change the application file since it will cause a lot conflicts right now). Also everything has tests except for Save and PartyCreator.

PS I need to get this branch merged before I can start working on battleEnd() so if you are free please review it.

2022-11-30 02:08 UTC, 6167656e74323431 requested changes
Please remove all the `.DS_Store` files.

2022-11-30 06:48 UTC, sbrad044 submitted a review, later dismissed

2022-11-30 21:51 UTC, 6167656e74323431 requested changes
All the problems are the usual style ones (missing javadoc, bad capitalization conventions, etc.)

2022-11-30 21:51 UTC, 6167656e74323431 commented on src/main/java/com/mg105/outputds/BattleCharacterDetails.java
> +    private final String NAME;
these are not true constants and so they should be `camelCase`

2022-11-30 21:51 UTC, 6167656e74323431 commented on src/main/java/com/mg105/outputds/BattleCharacterDetails.java
> +    private final String NAME;
(AFAIK `ALL_CAPS_WITH_UNDERSCORES` is reserved for only constants that are final and static)

2022-11-30 21:51 UTC, 6167656e74323431 commented on src/main/java/com/mg105/outputds/MoveDetails.java
> +    private final String NAME;
Not true constants, `camelCase`

2022-11-30 21:51 UTC, 6167656e74323431 commented on src/main/java/com/mg105/use_cases/PartyDataInterface.java
> +    /**
No description of what the method does? only parameters?

2022-11-30 21:51 UTC, 6167656e74323431 commented on src/main/java/com/mg105/use_cases/save/PartySaver.java
> +    private final GameState STATE;
`camelCase`

2022-11-30 22:36 UTC, m-grigoriu approved these changes
Everything looks good. The character names in Inventory tests should be based on the party constants since InventoryInteractor is coded to refer to that file.

2022-11-30 22:36 UTC, m-grigoriu commented on src/test/java/com/mg105/interface_adapters/inventory/InventoryControllerTest.java
> +    BattleCharacter b1 = new BattleCharacter(1, "A", 2, 3, false,
Probably change character names to reflect Party constants in case they change.

2022-12-01 15:15 UTC, m-grigoriu approved these changes
Looks good.

2022-12-01 19:37 UTC, 6167656e74323431 approved these changes

2022-12-02 02:49 UTC, sbrad044 approved these changes

2022-12-02 02:52 UTC, merged