replay game when entered final room
CSC207-2022F-UofT/course-project-group-105 pull request #84
Opened 2022-12-04 19:45 UTC by zhaoan12

when stepping into final room, replay game

2022-12-04 19:53 UTC, m-grigoriu approved these changes

2022-12-04 20:05 UTC, 6167656e74323431 commented
It is unclear when the game ends... it just feels like the game goes in an infinite loop (also the minimap does not get cleared and so it just keeps growing:

e.g.
![image](https://user-images.githubusercontent.com/29984862/205512883-9ac553aa-a8cb-4eee-afab-ca5f045ac3f3.png)

2022-12-04 22:05 UTC, 6167656e74323431 requested changes
Isn't there supposed to be a reward and some kind of indication when you beat the game? It's incredibly confusing when that happens currently, and afaik there isn't any reward.

Edit: we should probably also heal when you win.

2022-12-05 03:44 UTC, 6167656e74323431 requested changes

2022-12-05 03:44 UTC, 6167656e74323431 commented on src/main/java/com/mg105/interface_adapters/WinDisplay.java
> +public class WinDisplay implements PropertyChangeListener {
missing javadoc

2022-12-05 03:44 UTC, 6167656e74323431 commented on src/main/java/com/mg105/interface_adapters/WinDisplay.java
> +    public WinDisplay(Toggler toggler, RoomGetter roomGetter){
missing javadoc

2022-12-05 03:44 UTC, 6167656e74323431 commented on src/main/java/com/mg105/user_interface/WinMenu.java
> +public class WinMenu implements Toggleable {
missing javadoc

2022-12-05 03:44 UTC, 6167656e74323431 commented on src/main/java/com/mg105/user_interface/WinMenu.java
> +    public WinMenu(@NotNull ReplayGeneratorButton ReplayButton) {
missing javadoc

2022-12-05 03:44 UTC, 6167656e74323431 commented on src/main/java/com/mg105/user_interface/WinMenu.java
> +    @Override
missing javadoc

2022-12-05 03:44 UTC, 6167656e74323431 commented on src/main/java/com/mg105/user_interface/WinMenu.java
> +    @Override
missing javadoc

2022-12-05 04:05 UTC, 6167656e74323431 approved these changes

2022-12-05 04:07 UTC, siddharthgowda approved these changes

2022-12-05 15:33 UTC, m-grigoriu approved these changes
Looks good.

2022-12-05 15:45 UTC, merged